"""initial_phase_2_schema

Revision ID: 69a70707c4c5
Revises: 
Create Date: 2026-06-27 21:59:28.645038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69a70707c4c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), server_default='en', nullable=False),
    sa.Column('voice_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False, comment='draft_created, post_published, engagement_approved, etc.'),
    sa.Column('entity_type', sa.String(length=100), nullable=True, comment='post_draft, pending_engagement, graph_run, etc.'),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True, comment='Event-specific data'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('browser_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='kimi_webbridge or playwright'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='connected, disconnected, error'),
    sa.Column('browser_name', sa.String(length=50), nullable=True, comment='chrome, firefox, edge, etc.'),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True, comment='Provider-specific metadata (bridge version, capabilities, etc.)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_browser_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_browser_sessions'))
    )
    op.create_index(op.f('ix_browser_sessions_created_at'), 'browser_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_browser_sessions_id'), 'browser_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_browser_sessions_last_seen_at'), 'browser_sessions', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_browser_sessions_user_id'), 'browser_sessions', ['user_id'], unique=False)
    op.create_table('chat_history',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False, comment='user, assistant, system'),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('source_mode', sa.String(length=50), nullable=True, comment='text, voice'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_history_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_history'))
    )
    op.create_index(op.f('ix_chat_history_created_at'), 'chat_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_history_id'), 'chat_history', ['id'], unique=False)
    op.create_index(op.f('ix_chat_history_user_id'), 'chat_history', ['user_id'], unique=False)
    op.create_table('graph_runs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('graph_name', sa.String(length=100), nullable=False, comment='content_creation, engagement_review, etc.'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='running, waiting_human, completed, failed, cancelled'),
    sa.Column('current_node', sa.String(length=100), nullable=True, comment='Current or last executed node'),
    sa.Column('input_json', sa.JSON(), nullable=True, comment='Initial input'),
    sa.Column('result_json', sa.JSON(), nullable=True, comment='Final result'),
    sa.Column('error_json', sa.JSON(), nullable=True, comment='Error details if failed'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_graph_runs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_runs'))
    )
    op.create_index(op.f('ix_graph_runs_created_at'), 'graph_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_graph_runs_graph_name'), 'graph_runs', ['graph_name'], unique=False)
    op.create_index(op.f('ix_graph_runs_id'), 'graph_runs', ['id'], unique=False)
    op.create_index(op.f('ix_graph_runs_status'), 'graph_runs', ['status'], unique=False)
    op.create_index(op.f('ix_graph_runs_user_id'), 'graph_runs', ['user_id'], unique=False)
    op.create_table('linkedin_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.String(length=255), nullable=False, comment='LinkedIn member ID'),
    sa.Column('profile_url', sa.String(length=500), nullable=True),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_linkedin_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_linkedin_profiles'))
    )
    op.create_index(op.f('ix_linkedin_profiles_created_at'), 'linkedin_profiles', ['created_at'], unique=False)
    op.create_index(op.f('ix_linkedin_profiles_id'), 'linkedin_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_linkedin_profiles_member_id'), 'linkedin_profiles', ['member_id'], unique=True)
    op.create_index(op.f('ix_linkedin_profiles_user_id'), 'linkedin_profiles', ['user_id'], unique=True)
    op.create_table('oauth_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), server_default='linkedin', nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False, comment='LinkedIn member ID or sub from OpenID Connect'),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True, comment='Granted OAuth scopes (e.g., w_member_social)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oauth_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_accounts')),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_provider_user')
    )
    op.create_index(op.f('ix_oauth_accounts_created_at'), 'oauth_accounts', ['created_at'], unique=False)
    op.create_index(op.f('ix_oauth_accounts_id'), 'oauth_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_oauth_accounts_provider_user_id'), 'oauth_accounts', ['provider_user_id'], unique=False)
    op.create_index(op.f('ix_oauth_accounts_token_expires_at'), 'oauth_accounts', ['token_expires_at'], unique=False)
    op.create_index(op.f('ix_oauth_accounts_user_id'), 'oauth_accounts', ['user_id'], unique=False)
    op.create_table('watchlist',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_member_id', sa.String(length=255), nullable=False, comment='LinkedIn member ID to monitor'),
    sa.Column('target_profile_url', sa.String(length=500), nullable=False),
    sa.Column('target_name', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_watchlist_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watchlist')),
    sa.UniqueConstraint('user_id', 'target_member_id', name='uq_user_target')
    )
    op.create_index(op.f('ix_watchlist_created_at'), 'watchlist', ['created_at'], unique=False)
    op.create_index(op.f('ix_watchlist_id'), 'watchlist', ['id'], unique=False)
    op.create_index(op.f('ix_watchlist_is_active'), 'watchlist', ['is_active'], unique=False)
    op.create_index(op.f('ix_watchlist_target_member_id'), 'watchlist', ['target_member_id'], unique=False)
    op.create_index(op.f('ix_watchlist_user_id'), 'watchlist', ['user_id'], unique=False)
    op.create_table('pending_engagements',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('graph_run_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False, comment='comment_reply, watchlist_post, etc.'),
    sa.Column('source_post_url', sa.String(length=500), nullable=True),
    sa.Column('source_post_urn', sa.String(length=255), nullable=True),
    sa.Column('target_member_id', sa.String(length=255), nullable=True, comment='LinkedIn member ID of target'),
    sa.Column('action_type', sa.String(length=50), nullable=False, comment='like, celebrate, support, insightful, comment'),
    sa.Column('suggested_text', sa.Text(), nullable=True, comment='Suggested comment text if action_type=comment'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='pending, approved, skipped, posted, failed'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['graph_run_id'], ['graph_runs.id'], name=op.f('fk_pending_engagements_graph_run_id_graph_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_pending_engagements_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pending_engagements'))
    )
    op.create_index(op.f('ix_pending_engagements_created_at'), 'pending_engagements', ['created_at'], unique=False)
    op.create_index(op.f('ix_pending_engagements_graph_run_id'), 'pending_engagements', ['graph_run_id'], unique=False)
    op.create_index(op.f('ix_pending_engagements_id'), 'pending_engagements', ['id'], unique=False)
    op.create_index(op.f('ix_pending_engagements_source_post_urn'), 'pending_engagements', ['source_post_urn'], unique=False)
    op.create_index(op.f('ix_pending_engagements_status'), 'pending_engagements', ['status'], unique=False)
    op.create_index(op.f('ix_pending_engagements_user_id'), 'pending_engagements', ['user_id'], unique=False)
    op.create_table('posts_drafted',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('graph_run_id', sa.UUID(), nullable=True),
    sa.Column('idea_input', sa.Text(), nullable=False, comment='Original user idea'),
    sa.Column('draft_text', sa.Text(), nullable=False, comment='Generated draft text'),
    sa.Column('variant_index', sa.Integer(), nullable=False, comment='Draft variant number (0, 1, 2)'),
    sa.Column('score', sa.Integer(), nullable=True, comment='Score 0-100 from evaluation'),
    sa.Column('score_breakdown_json', sa.JSON(), nullable=True, comment='Detailed score breakdown and reasoning'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='drafted, approved, posted, failed'),
    sa.Column('final_text', sa.Text(), nullable=True, comment='User-edited final text before posting'),
    sa.Column('linkedin_post_url', sa.String(length=500), nullable=True),
    sa.Column('linkedin_post_urn', sa.String(length=255), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['graph_run_id'], ['graph_runs.id'], name=op.f('fk_posts_drafted_graph_run_id_graph_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_posts_drafted_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts_drafted'))
    )
    op.create_index(op.f('ix_posts_drafted_created_at'), 'posts_drafted', ['created_at'], unique=False)
    op.create_index(op.f('ix_posts_drafted_graph_run_id'), 'posts_drafted', ['graph_run_id'], unique=False)
    op.create_index(op.f('ix_posts_drafted_id'), 'posts_drafted', ['id'], unique=False)
    op.create_index(op.f('ix_posts_drafted_linkedin_post_urn'), 'posts_drafted', ['linkedin_post_urn'], unique=False)
    op.create_index(op.f('ix_posts_drafted_posted_at'), 'posts_drafted', ['posted_at'], unique=False)
    op.create_index(op.f('ix_posts_drafted_status'), 'posts_drafted', ['status'], unique=False)
    op.create_index(op.f('ix_posts_drafted_user_id'), 'posts_drafted', ['user_id'], unique=False)
    op.drop_index(op.f('checkpoint_writes_thread_id_idx'), table_name='checkpoint_writes')
    op.drop_table('checkpoint_writes')
    op.drop_index(op.f('checkpoints_thread_id_idx'), table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_table('checkpoint_migrations')
    op.drop_index(op.f('checkpoint_blobs_thread_id_idx'), table_name='checkpoint_blobs')
    op.drop_table('checkpoint_blobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False)
    op.drop_index(op.f('ix_posts_drafted_user_id'), table_name='posts_drafted')
    op.drop_index(op.f('ix_posts_drafted_status'), table_name='posts_drafted')
    op.drop_index(op.f('ix_posts_drafted_posted_at'), table_name='posts_drafted')
    op.drop_index(op.f('ix_posts_drafted_linkedin_post_urn'), table_name='posts_drafted')
    op.drop_index(op.f('ix_posts_drafted_id'), table_name='posts_drafted')
    op.drop_index(op.f('ix_posts_drafted_graph_run_id'), table_name='posts_drafted')
    op.drop_index(op.f('ix_posts_drafted_created_at'), table_name='posts_drafted')
    op.drop_table('posts_drafted')
    op.drop_index(op.f('ix_pending_engagements_user_id'), table_name='pending_engagements')
    op.drop_index(op.f('ix_pending_engagements_status'), table_name='pending_engagements')
    op.drop_index(op.f('ix_pending_engagements_source_post_urn'), table_name='pending_engagements')
    op.drop_index(op.f('ix_pending_engagements_id'), table_name='pending_engagements')
    op.drop_index(op.f('ix_pending_engagements_graph_run_id'), table_name='pending_engagements')
    op.drop_index(op.f('ix_pending_engagements_created_at'), table_name='pending_engagements')
    op.drop_table('pending_engagements')
    op.drop_index(op.f('ix_watchlist_user_id'), table_name='watchlist')
    op.drop_index(op.f('ix_watchlist_target_member_id'), table_name='watchlist')
    op.drop_index(op.f('ix_watchlist_is_active'), table_name='watchlist')
    op.drop_index(op.f('ix_watchlist_id'), table_name='watchlist')
    op.drop_index(op.f('ix_watchlist_created_at'), table_name='watchlist')
    op.drop_table('watchlist')
    op.drop_index(op.f('ix_oauth_accounts_user_id'), table_name='oauth_accounts')
    op.drop_index(op.f('ix_oauth_accounts_token_expires_at'), table_name='oauth_accounts')
    op.drop_index(op.f('ix_oauth_accounts_provider_user_id'), table_name='oauth_accounts')
    op.drop_index(op.f('ix_oauth_accounts_id'), table_name='oauth_accounts')
    op.drop_index(op.f('ix_oauth_accounts_created_at'), table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    op.drop_index(op.f('ix_linkedin_profiles_user_id'), table_name='linkedin_profiles')
    op.drop_index(op.f('ix_linkedin_profiles_member_id'), table_name='linkedin_profiles')
    op.drop_index(op.f('ix_linkedin_profiles_id'), table_name='linkedin_profiles')
    op.drop_index(op.f('ix_linkedin_profiles_created_at'), table_name='linkedin_profiles')
    op.drop_table('linkedin_profiles')
    op.drop_index(op.f('ix_graph_runs_user_id'), table_name='graph_runs')
    op.drop_index(op.f('ix_graph_runs_status'), table_name='graph_runs')
    op.drop_index(op.f('ix_graph_runs_id'), table_name='graph_runs')
    op.drop_index(op.f('ix_graph_runs_graph_name'), table_name='graph_runs')
    op.drop_index(op.f('ix_graph_runs_created_at'), table_name='graph_runs')
    op.drop_table('graph_runs')
    op.drop_index(op.f('ix_chat_history_user_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_created_at'), table_name='chat_history')
    op.drop_table('chat_history')
    op.drop_index(op.f('ix_browser_sessions_user_id'), table_name='browser_sessions')
    op.drop_index(op.f('ix_browser_sessions_last_seen_at'), table_name='browser_sessions')
    op.drop_index(op.f('ix_browser_sessions_id'), table_name='browser_sessions')
    op.drop_index(op.f('ix_browser_sessions_created_at'), table_name='browser_sessions')
    op.drop_table('browser_sessions')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
