"""change graph_run_id from UUID to String for LangGraph thread_ids

Revision ID: a1b2c3d4e5f6
Revises: 69a70707c4c5
Create Date: 2026-06-30 19:16:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '69a70707c4c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Drop foreign key constraints
    op.drop_constraint(
        'fk_posts_drafted_graph_run_id_graph_runs',
        'posts_drafted',
        type_='foreignkey'
    )
    op.drop_constraint(
        'fk_pending_engagements_graph_run_id_graph_runs',
        'pending_engagements',
        type_='foreignkey'
    )

    # 2. Alter graph_run_id columns from UUID to String(255)
    op.alter_column(
        'posts_drafted',
        'graph_run_id',
        existing_type=sa.UUID(),
        type_=sa.String(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        'pending_engagements',
        'graph_run_id',
        existing_type=sa.UUID(),
        type_=sa.String(length=255),
        existing_nullable=True,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Revert columns back to UUID
    op.alter_column(
        'posts_drafted',
        'graph_run_id',
        existing_type=sa.String(length=255),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    op.alter_column(
        'pending_engagements',
        'graph_run_id',
        existing_type=sa.String(length=255),
        type_=sa.UUID(),
        existing_nullable=True,
    )

    # 2. Recreate foreign key constraints
    op.create_foreign_key(
        'fk_posts_drafted_graph_run_id_graph_runs',
        'posts_drafted',
        'graph_runs',
        ['graph_run_id'],
        ['id'],
        ondelete='SET NULL'
    )
    op.create_foreign_key(
        'fk_pending_engagements_graph_run_id_graph_runs',
        'pending_engagements',
        'graph_runs',
        ['graph_run_id'],
        ['id'],
        ondelete='SET NULL'
    )

    # ### end Alembic commands ###
